/* ===========================================================
   Les répliques des croupiers — par personnage ET par tenue.
   Ton : vulgaire, méprisant, ou franchement jouissif quand tu perds.

   Structure : CROUPIER_LINES[gender][skinIndex] = {
     launch: [10], play: [20], lose: [10], win: [10]
   }
   Le tirage SANS RÉPÉTITION est géré dans croupier.js (sac mélangé).
   =========================================================== */

const CROUPIER_LINES = {

  /* ============================ CROUPIER (Blackjack) ============================ */
  men: {

    // 0 — Smoking rubis : l'arrogant classique
    0: {
      launch: [
        "Tiens, revoilà le portefeuille sur pattes.",
        "Assieds-toi. J'ai des factures à payer avec ton argent.",
        "Encore toi ? Ma banque te remercie d'avance.",
        "Approche, victime numéro un du jour.",
        "T'as remis les mêmes fringues que ta dernière défaite, j'aime la cohérence.",
        "Je préviens la maison : le pigeon est de retour.",
        "Une chaise pour monsieur… ou madame la ruine.",
        "T'as le regard de quelqu'un qui va tout perdre. Ça me plaît.",
        "Range ta chance dans ta poche, elle sert à rien ici.",
        "On parie combien que tu repars à poil ?",
      ],
      play: [
        "Tu réfléchis ? Original.",
        "Prends une carte, prends deux cartes, prends la sortie.",
        "T'as la même tête que ton solde : vide.",
        "Vas-y, tire. Fais-moi rire.",
        "C'est pas de la stratégie, c'est de la comédie.",
        "Je bâille. Décide.",
        "Chaque seconde tu perds un peu plus, continue.",
        "T'as vu tes cartes ? Moi oui, et j'ai pitié.",
        "Ta main pue la défaite d'ici.",
        "Encore un pari débile, magnifique.",
        "Tu joues comme mon grille-pain, sauf que lui il gagne parfois.",
        "T'inquiète, la maison est là pour te consoler… en encaissant.",
        "Reste concentré, ça change rien mais c'est mignon.",
        "Tu transpires ? Bonne nouvelle : c'est ton seul liquide qui bouge.",
        "Tire. Ou pas. De toute façon t'es cuit.",
        "Ce jeton, dis-lui adieu maintenant, ça t'évitera la surprise.",
        "T'as un plan ? Adorable.",
        "Je sens la banqueroute, et ça sent bon.",
        "Doucement, savoure ta dernière minute de riche.",
        "T'es venu perdre avec classe au moins, j'apprécie l'effort.",
      ],
      lose: [
        "HA. Merci pour le pourboire involontaire.",
        "Et voilà, encore un rêve qui finit dans ma caisse.",
        "T'as perdu. Comme hier. Comme demain.",
        "Ne pleure pas sur le tapis, je viens de le faire nettoyer.",
        "Ça, c'était pathétique. Refais-le.",
        "Ton argent est plus heureux avec moi, crois-moi.",
        "Regarde-moi ranger tes jetons. Lentement. Exprès.",
        "T'as la poisse ou t'es juste nul ? Les deux, sûrement.",
        "Un vrai talent pour perdre. Bravo, sincèrement.",
        "La sortie est à gauche. Ton dignité, elle, est restée sur la table.",
      ],
      win: [
        "Profite. Ça durera pas.",
        "T'as gagné ? La machine a dû buguer.",
        "Un coup de bol. Un seul. Note-le dans ton journal intime.",
        "Vas-y, souris. J'aime voir un pigeon se croire aigle.",
        "Rejoue tout de suite, tant que t'y crois encore.",
        "La chance t'a rendu visite. Elle repartira sans prévenir.",
        "Félicitations, tu m'as coûté un café.",
        "Garde ça au chaud, je viens le rechercher dans deux minutes.",
        "T'as gagné une bataille. Moi j'ai déjà gagné la guerre.",
        "Tu crois avoir compris le jeu. C'est trop mignon.",
      ],
    },

    // 1 — Chef flambeur : tout passe à la casserole
    1: {
      launch: [
        "Bienvenue en cuisine. Aujourd'hui : ton portefeuille en croûte.",
        "J'ai allumé le feu. Tu vas mijoter longtemps.",
        "Amène-toi, petit poulet, la poêle est chaude.",
        "Au menu : humiliation, sauce ruine, et toi en dessert.",
        "Enfile ton bavoir, ça va gicler.",
        "Je te sens tendre. Parfait pour un carpaccio de faillite.",
        "La maison mijote ta défaite depuis ce matin.",
        "T'as réservé une table ? Une pour pleurer, alors.",
        "Sers-toi un verre, ce sera ta seule victoire.",
        "Commençons la cuisson. À feu vif, comme ta ruine.",
      ],
      play: [
        "Tu laisses réduire ? Ton solde aussi réduit, tiens.",
        "Une pincée de bêtise, et hop, plat raté.",
        "Ça sent le cramé. Ah non, c'est juste ta stratégie.",
        "Goûte-moi cette carte. Elle a un goût de défaite.",
        "Trop cuit. Trop tard. Trop toi.",
        "Tu touilles, tu touilles, et ça tourne quand même à la catastrophe.",
        "Mets le couvercle, ça pue l'échec.",
        "Encore une louche de malchance dans ton assiette ?",
        "T'as pas le coup de main. T'as pas le coup tout court.",
        "Ce jeton, je le fais flamber. Comme ton compte en banque.",
        "Doucement le feu, tu vas te brûler les doigts et le reste.",
        "Ta recette du succès : introuvable, comme ton talent.",
        "Je dresse l'assiette : néant, réduction de néant, coulis de néant.",
        "T'as oublié le sel. Et le cerveau.",
        "Ça mijote… ça mijote… et ça va être immonde.",
        "Un vrai marmiton perdrait avec plus de dignité.",
        "Tu remues le pot, le pot te remue. Match nul jusqu'à ta faillite.",
        "Feu doux pour toi : je préfère te voir souffrir longtemps.",
        "Ta main sent le poisson pas frais.",
        "Encore une fournée ? Elle sera aussi brûlée que la précédente.",
      ],
      lose: [
        "Et voilà, servi bien chaud : ta ruine, à table !",
        "Trop cuit. On jette. Toi avec.",
        "Ça, c'est un plat qui restera dans les annales des ratages.",
        "J'ai flambé ton jeton. Joli feu, non ?",
        "Retour en cuisine, marmiton, t'as encore tout cramé.",
        "Ton portefeuille est carbonisé. Parfait pour mes toasts.",
        "La note, s'il te plaît. Ah, tu peux plus payer. Dommage.",
        "Un fiasco al dente. Croquant à souhait.",
        "Je garde les restes. C'est-à-dire tout ton argent.",
        "Plat du jour : la déprime, avec supplément larmes.",
      ],
      win: [
        "T'as réussi un plat ? La chance a dû s'endormir sur le fourneau.",
        "Bon, un coup potable. Le prochain sera immangeable, promis.",
        "Savoure vite, ça va refroidir et retomber dans ma caisse.",
        "Petit miracle de cuisine. Ça n'arrivera plus.",
        "Tu m'as piqué une bouchée. J'ai encore tout le buffet.",
        "Rejoue tant que le four est chaud, ça t'évitera d'y penser.",
        "Un succès ? Note la date, c'est un événement rare.",
        "T'as gagné une entrée. Le plat et l'addition sont pour moi.",
        "La chance t'a servi. Le service est fini.",
        "Belle assiette. Vide-la vite, je récupère la vaisselle.",
      ],
    },

    // 2 — Costume saphir : le requin en trois pièces
    2: {
      launch: [
        "Le marché ouvre. Toi, tu vas plonger.",
        "Bonjour. Je liquide tes actifs dès la première main.",
        "Investisseur du dimanche, assieds-toi, on va parler pertes.",
        "Ton capital ? Considère-le comme une donation.",
        "J'aime les clients comme toi : liquides et faciles à essorer.",
        "Signe ici, ici, et là — c'est le contrat de ta faillite.",
        "Portefeuille ouvert, cerveau fermé. Le combo parfait.",
        "On démarre la réunion. Ordre du jour : ta ruine.",
        "T'as le profil risque « catastrophe ». Idéal.",
        "Le temps, c'est de l'argent. Et là, tu perds les deux.",
      ],
      play: [
        "Ta position se détériore. Comme ton visage.",
        "Décision lente = argent perdu. C'est mathématique.",
        "Tu spécules sur ta chance ? Actif pourri.",
        "Le rendement de ta stratégie : moins l'infini.",
        "Tiens, la courbe de ton solde. Elle plonge, comme le Titanic.",
        "Chaque jeton misé, c'est un dividende pour moi.",
        "T'analyses ? Adorable. Le résultat est déjà écrit.",
        "Diversifie tes pertes, au moins.",
        "Ton bilan comptable tient sur un post-it. Vide.",
        "La bulle va éclater. La tienne. Sur ta tête.",
        "Achète, vends, perds. Surtout perds.",
        "T'es short sur la vie, mon vieux.",
        "Le conseil d'administration me dit de te plumer. Je suis d'accord.",
        "Volatilité maximale : ton compte, dans dix secondes.",
        "T'as un stop-loss ? Non ? Évidemment.",
        "Je facture chaque minute de ta bêtise. Continue.",
        "Ce jeton est déjà dans mes comptes. Formalité.",
        "Tu joues au trader. Moi je suis la crise de 29.",
        "Ta trésorerie : rouge. Comme tes yeux bientôt.",
        "Encore un pari ? J'adore les mauvais placements.",
      ],
      lose: [
        "Transaction validée : tout ton argent, vers moi. Merci.",
        "Faillite personnelle. Aucun plan de sauvetage prévu.",
        "J'encaisse. Toi, tu déprécies.",
        "Ton portefeuille vient de faire -100 %. Record.",
        "La séance est close. Toi aussi, financièrement.",
        "Actif toxique liquidé. C'était toi.",
        "Je garde tes jetons en portefeuille long terme. Très long.",
        "Krach. Total. Silencieux. Comme ta dignité.",
        "Le marché a parlé : t'es nul.",
        "Bilan de la journée : moi riche, toi à sec. Classique.",
      ],
      win: [
        "Petit gain. L'exception qui confirme la ruine.",
        "T'as touché un dividende. Le capital reste à moi.",
        "Rebond technique. Suivi d'une chute libre, garanti.",
        "Encaisse vite, avant la correction.",
        "Un bon trade sur mille. Les statistiques te haïssent.",
        "Tu crois avoir battu le marché. Le marché rigole.",
        "Réinvestis tout, tout de suite. Fais-moi confiance. Ou pas.",
        "T'as grappillé. Moi j'ai le coffre.",
        "La chance, c'est un actif que tu ne possèdes pas.",
        "Profit à court terme, misère à long terme. Deal ?",
      ],
    },

    // 3 — Grand magicien : abracadabra, t'es ruiné
    3: {
      launch: [
        "Mesdames et messieurs… voici le pigeon disparaissant !",
        "Ce soir : je fais s'évanouir ton argent. Sans trucage.",
        "Choisis une carte. N'importe laquelle. Elles te trahiront toutes.",
        "Le tour commence. La fin est déjà écrite dans ma manche.",
        "Un peu de fumée, et pouf, ton solde n'existe plus.",
        "Approche du chapeau. Y a plus rien dedans, comme dans ta poche bientôt.",
        "Illusion numéro un : tu crois que tu peux gagner.",
        "Roulement de tambour… pour ta chute.",
        "Je vais deviner ta main. Et ton avenir : sombre.",
        "Tada. T'es déjà perdant et le jeu n'a pas commencé.",
      ],
      play: [
        "Regarde bien ma main gauche… pendant que la droite vide ton compte.",
        "Concentre-toi. L'échec, lui, est déjà concentré sur toi.",
        "Un claquement de doigts, et ta stratégie s'envole.",
        "Ta carte va se transformer… en déception.",
        "Le public retient son souffle. Toi tu retiens tes larmes.",
        "Abracadabra : ce jeton n'est plus à toi.",
        "Illusion d'optique : tu croyais avoir une bonne main.",
        "Je lis dans tes pensées. Y a pas grand-chose.",
        "Le lapin est mort. La métaphore aussi, comme ton espoir.",
        "Fais un vœu sur cette carte. Il sera pas exaucé.",
        "Tour de passe-passe : ton argent passe chez moi, ça se passe mal pour toi.",
        "Un peu de patience, la trappe va s'ouvrir sous tes pieds.",
        "Ta main dans mon jeu, c'est un pigeon dans un chapeau.",
        "Prestidigitation : je fais apparaître ta ruine.",
        "Le miroir te ment. Il te dit que t'as une chance.",
        "Encore un pari ? Le grand final approche.",
        "Concentration… lévitation… humiliation.",
        "Je coupe le jeu. Et tes espoirs.",
        "Tu vois cette carte ? Non ? Normal, c'est ma spécialité.",
        "Le rideau va tomber. Sur ta tête.",
      ],
      lose: [
        "TADA ! Ton argent a disparu. Applaudissez.",
        "Tour réussi : plus rien dans ta poche.",
        "Le pigeon s'est envolé sans ses jetons. Magnifique.",
        "Illusion terminée. La ruine, elle, est bien réelle.",
        "J'ai fait disparaître ton solde. Impossible à retrouver.",
        "Le public adore. Toi, un peu moins.",
        "Abracadabra, dans mon coffre-fort.",
        "Tu voulais du spectacle ? Voilà ta banqueroute en direct.",
        "Le chapeau est vide. Comme ton compte. Comme ton crâne.",
        "Fin du numéro. Sors par la trappe, comme un vrai perdant.",
      ],
      win: [
        "Ton seul tour de magie : gagner une fois. Bravo, l'amateur.",
        "La chance t'a prêté sa baguette. Elle veut la récupérer.",
        "Illusion de victoire. Le vrai final arrive.",
        "T'as fait apparaître un gain. Je le fais disparaître au prochain coup.",
        "Applaudissements polis. Rejoue avant qu'ils s'arrêtent.",
        "Un coup de baguette bien placé. Le hasard se moque de toi.",
        "Garde ce gain sous ton chapeau. Je viens le chercher.",
        "Tu crois maîtriser le tour. Tu es le tour.",
        "Beau numéro. Maintenant le clou du spectacle : ta rechute.",
        "La magie, c'est éphémère. Ta ruine, elle, est solide.",
      ],
    },

    // 4 — Escale plage : je bosse en tongs, toi tu coules
    4: {
      launch: [
        "Salut. Je suis en vacances, toi t'es en galère.",
        "Pose ton parasol, l'orage financier arrive.",
        "Cocktail à la main, je vais te noyer tranquille.",
        "T'as mis de la crème ? Ça t'évitera pas de cramer ici.",
        "Bienvenue au club plage : entrée gratuite, sortie ruinée.",
        "J'ai le temps. Toi non, ton argent part avec la marée.",
        "Assieds-toi sur le sable, ça amortira ta chute.",
        "Le soleil brille, ton compte, lui, s'assombrit.",
        "Un dernier bain avant la noyade ?",
        "Tranquille. Je te plume au ralenti, façon farniente.",
      ],
      play: [
        "T'énerve pas, on est à la plage. Perds cool.",
        "La vague arrive… elle emporte ton jeton.",
        "Molo. Prends ton temps pour couler.",
        "T'as du sable dans le cerveau ou c'est naturel ?",
        "Sirote ton verre, c'est ton dernier luxe.",
        "Je bronze pendant que tu te ruines. Vie parfaite.",
        "Ta stratégie a la consistance d'un château de sable.",
        "Le courant t'entraîne. Vers le fond.",
        "Bouge pas, un requin (moi) tourne autour de tes économies.",
        "Encore une carte ? T'as vraiment rien d'autre à faire de tes sous.",
        "Ça sent la crème solaire et la défaite.",
        "T'as pris un coup de soleil sur le jugement.",
        "La mer monte. Ton solde baisse. C'est l'équilibre.",
        "Détends-toi, la ruine c'est plus doux quand on résiste pas.",
        "Un transat pour monsieur… ou madame la faillite ?",
        "Je fais la planche. Toi tu fais naufrage.",
        "Ce jeton, la marée l'a déjà pris.",
        "Ambiance chill, portefeuille en feu.",
        "T'entends les mouettes ? Elles se foutent de toi.",
        "Encore un pari mou du genou.",
      ],
      lose: [
        "Splash. Ton argent au fond de l'eau.",
        "Marée basse sur ton compte. Très basse.",
        "T'as coulé. Tranquillement, mais sûrement.",
        "Le sable a bu tes jetons. Moi aussi j'ai soif, ressers-toi.",
        "Nofrage complet. Même les crabes ont pitié.",
        "Ton château de sable s'est effondré. Comme prévu.",
        "La vague a tout pris. Reviens demain, y aura une autre vague.",
        "T'es sec. Et pas à cause du soleil.",
        "Retour à la serviette, matelot, t'as tout perdu.",
        "Repose-toi. T'as bien mérité ta faillite.",
      ],
      win: [
        "Oh, une petite vague de chance. Ça va se retirer.",
        "T'as attrapé un coquillage. Moi j'ai la plage entière.",
        "Profite du soleil, l'orage arrive au prochain coup.",
        "Un gain ? La mer a dû se tromper de client.",
        "Rejoue vite, avant que la marée reprenne tout.",
        "Beau plongeon. Le prochain sera dans le vide.",
        "Garde ça au frais dans la glacière. Je viens me servir.",
        "La chance t'a effleuré comme une méduse. Ça va piquer plus tard.",
        "T'as gagné un tour de bouée. Le bateau coule quand même.",
        "Tu crois surfer. Tu vas boire la tasse.",
      ],
    },
  },

  /* ============================ CROUPIÈRE (Poker) ============================ */
  women: {

    // 0 — Robe cabaret : la femme fatale qui te ruine en souriant
    0: {
      launch: [
        "Rebonjour, mon chou. Ton argent m'a manqué.",
        "Assieds-toi. Je vais te dépouiller avec le sourire.",
        "Oh, un client. Ou plutôt : un futur ex-riche.",
        "Approche, beau gosse. Enfin… approche quand même.",
        "J'adore ton parfum. Ça sent la défaite imminente.",
        "On va bien s'amuser. Enfin, moi.",
        "T'as ramené ton portefeuille ? C'est mignon, il va rester chez moi.",
        "Un verre ? Tu vas en avoir besoin.",
        "Regarde-moi dans les yeux pendant que je vide ta poche.",
        "Bienvenue au spectacle. Tu es le numéro comique.",
      ],
      play: [
        "Tu bluffes ? Ta lèvre tremble, trésor.",
        "Prends ton temps. Chaque seconde te coûte cher.",
        "Cette main… j'ai presque de la peine. Presque.",
        "Décide, mon lapin. Le suspense me lasse.",
        "T'as les mains moites. Adorable. Et révélateur.",
        "Mise, chéri. J'ai une robe à m'offrir avec tes jetons.",
        "Tu me regardes ou tu regardes tes cartes ? Les deux te trahissent.",
        "Un petit pari nerveux, comme je les aime.",
        "T'as le regard fuyant. Tu vas fuir tout court, sans ton argent.",
        "Continue de transpirer, ça humidifie l'ambiance.",
        "Ce jeton te dit au revoir. Il part vivre chez moi.",
        "Ta stratégie est aussi transparente que ma robe.",
        "Joue, mon cœur. Le tapis a soif.",
        "T'as cru m'impressionner ? On m'a fait pire au petit-déjeuner.",
        "Doucement. Savoure d'être encore solvable.",
        "Tu tapotes la table. Signe universel de panique.",
        "Encore une relance ratée, quel charme.",
        "Je sens la faillite, et c'est un délicieux parfum.",
        "T'as une paire ? Moi j'ai le casino.",
        "Vas-y, mise gros. Fais-moi plaisir avant de pleurer.",
      ],
      lose: [
        "Aww. Tu as tout perdu. Viens là que je… non, en fait, dégage.",
        "Merci pour les jetons, mon ange. Et pour le spectacle.",
        "Tu perds avec tellement de constance. C'est presque touchant.",
        "Ne pleure pas, tu vas faire couler mon mascara de rire.",
        "Ton argent est plus heureux dans mon décolleté.",
        "C'était… comment dire… lamentable. Encore ?",
        "Je range tes rêves dans ma caisse. Ils tiennent pas de place.",
        "Un baiser d'adieu à tes jetons ? Trop tard, ils sont à moi.",
        "T'as la poisse ou t'es juste transparent ? Devinette facile.",
        "La porte est là-bas, chéri. Ton portefeuille reste ici.",
      ],
      win: [
        "Oh, une victoire. La chance a un faible pour les losers, on dirait.",
        "Profite, beau parleur. Je reprends tout dans deux minutes.",
        "T'as gagné ? J'ai dû cligner des yeux au mauvais moment.",
        "Souris tant que tu peux. Ça te va bien, la naïveté.",
        "Rejoue tout de suite, mon cœur, tant que t'y crois.",
        "Un coup de bol. Un. Encadre-le.",
        "Tu m'as pris un jeton. J'ai la robe, les bijoux et le reste.",
        "La chance t'a embrassé. Elle embrasse mal, tu verras.",
        "Garde ça au chaud, je viens le chercher, avec les intérêts.",
        "Tu crois m'avoir séduite. Tu m'as juste amusée.",
      ],
    },

    // 1 — Belle du Far West : dégaine plus vite que ton portefeuille
    1: {
      launch: [
        "Bienvenue au saloon, l'étranger. On sort d'ici plus pauvre.",
        "Pose ton flingue et ton fric. Le second m'intéresse.",
        "T'as la gâchette lente et le porte-monnaie généreux. Parfait.",
        "Assieds-toi, cow-boy du dimanche.",
        "Y a un avis de recherche sur ta chance. Morte ou vive. Plutôt morte.",
        "On joue au poker, pas à cache-cache avec ta dignité.",
        "Le shérif, c'est moi. La loi, c'est : tu perds.",
        "Crache ta mise, l'ami. Et pas dans le crachoir.",
        "Un whisky pour la route de la ruine ?",
        "Duel au tapis. Tu dégaines… et tu rates.",
      ],
      play: [
        "Ta main tremble. C'est le canyon du vide.",
        "Mise, sinon je te colle dans la diligence des perdants.",
        "T'as un tell gros comme le Grand Canyon.",
        "Réfléchis vite, le soleil se couche sur ton compte.",
        "T'es dans un cul-de-sac, l'étranger. Avec moi au bout.",
        "Ce jeton part au galop. Chez moi.",
        "Tu bluffes comme un serpent édenté.",
        "La poussière retombe. Ta chance aussi.",
        "T'as sorti la mauvaise carte du holster.",
        "Encore un pari qui sent la sciure et l'échec.",
        "Le train de ta fortune vient de dérailler.",
        "T'as les yeux qui vrillent. Signe de reddition.",
        "Mise gros ou plie, y a pas de troisième option, sauf pleurer.",
        "Le lasso est autour de tes économies. Je tire.",
        "T'as le charisme d'un cactus et la chance d'un poulet.",
        "Doucement sur la détente, tu vas te tirer une balle dans le solde.",
        "Encore une relance foireuse. Yee-haw, pour moi.",
        "Le désert est vaste. Comme le trou dans ton budget.",
        "T'as une paire de bottes et une paire de deux. Insuffisant.",
        "Vas-y, l'étranger. Fais ton dernier pari de riche.",
      ],
      lose: [
        "Bang. T'es à terre, les poches retournées.",
        "La ville est à moi. Ton or aussi.",
        "On t'enterre au cimetière des joueurs fauchés.",
        "T'as mordu la poussière. Et elle avait meilleur goût que ta stratégie.",
        "Le train part sans toi et sans ton argent.",
        "Duel terminé. J'ai tiré, t'as payé.",
        "Ramasse ton chapeau, laisse tes jetons.",
        "Le shérif confisque tout. C'est la loi de l'Ouest.",
        "T'as le regard d'un homme qui vient de tout claquer. Parce que c'est le cas.",
        "Retourne à ton ranch, y a plus rien à jouer ici.",
      ],
      win: [
        "T'as touché une pépite. La mine est à moi.",
        "Un coup de chance de bleu. Ça arrive une fois par décennie.",
        "Profite, l'étranger. La prochaine balle est pour ton portefeuille.",
        "T'as gagné le duel. Pas la guerre des sioux.",
        "Rejoue avant que la chance change de saloon.",
        "La roue de la fortune t'a effleuré. Elle écrase, d'habitude.",
        "Garde ton or, je viens te dévaliser plus tard.",
        "Beau tir. Le prochain finira dans le sable.",
        "Tu crois être le kid le plus rapide de l'Ouest. T'es le plus fauché.",
        "Un gain honnête. Ça me dégoûte presque.",
      ],
    },

    // 2 — Salon victorien : le mépris en dentelle
    2: {
      launch: [
        "Quelle audace de vous présenter ici avec si peu de fortune.",
        "Asseyez-vous. Tâchez de perdre avec un minimum de tenue.",
        "Ah. Le vulgaire est de retour. Servez-lui un thé, qu'il patiente avant la ruine.",
        "On m'a dit que vous jouiez mal. On m'a menti : c'est pire.",
        "Votre présence rehausse le niveau… de mes gains.",
        "Retirez votre chapeau. Vous allez bientôt retirer tout le reste, financièrement.",
        "Un roturier à ma table. Comme c'est distrayant.",
        "Je vais vous dépouiller avec la plus grande élégance.",
        "Votre bourse a l'air lourde. Ce ne sera pas long.",
        "Prenez place. Le déshonneur financier vous attend.",
      ],
      play: [
        "Cette hésitation est d'un commun affligeant.",
        "Misez, je vous prie. Mon temps vaut plus que votre héritage.",
        "Vos manières trahissent votre jeu : médiocres.",
        "On ne bluffe pas avec cette transpiration, voyons.",
        "Quelle main disgracieuse. J'en rougirais à votre place.",
        "Ce jeton retourne dans la bonne société. La mienne.",
        "Votre stratégie manque cruellement d'éducation.",
        "Vous tremblez comme une feuille de thé.",
        "Décidez. La vulgarité de l'indécision m'écœure.",
        "Encore une mise de parvenu.",
        "Votre fortune s'effrite comme un biscuit sec.",
        "Vos yeux fuient. Comme votre honneur.",
        "Relancez, si tant est que vous compreniez le mot.",
        "Je confisque poliment vos illusions.",
        "Un joueur de votre rang devrait perdre plus discrètement.",
        "Doucement, savourez ces dernières secondes de respectabilité.",
        "Encore une relance grossière. Charmant.",
        "Le déclin de votre maison sera à la hauteur de votre jeu.",
        "Vous avez une paire ? Moi, une lignée entière de gains.",
        "Allons, misez gros. Que votre chute soit au moins spectaculaire.",
      ],
      lose: [
        "Et voilà. Vous vous êtes ruiné avec un manque total de style.",
        "Je récupère vos biens. Ils seront mieux tenus.",
        "Quelle déchéance. Presque digne d'un roman.",
        "Ne salissez pas mon tapis de vos larmes de nouveau riche.",
        "Votre bourse rejoint ma collection. Section « pigeons ».",
        "C'était affligeant. Recommencez, pour mon amusement.",
        "La domesticité vous raccompagnera. Vos jetons restent.",
        "Un désastre exécuté sans la moindre grâce.",
        "Vous avez la poisse et l'éducation d'un âne.",
        "La sortie, je vous prie. Votre dignité, elle, est déjà partie.",
      ],
      win: [
        "Vous avez gagné. Un accident de parcours, sans doute.",
        "Savourez. La roue tourne, et elle vous méprise.",
        "Une victoire ? Le hasard a des goûts douteux.",
        "Souriez, cela masque un instant votre médiocrité.",
        "Rejouez immédiatement, tant que l'illusion dure.",
        "Un coup de chance isolé. Ne vous croyez pas gentilhomme pour autant.",
        "Vous m'avez pris un jeton. Je possède le domaine.",
        "La fortune vous a fait l'aumône. Elle reviendra la reprendre.",
        "Gardez cela. Je viendrai le récupérer avec les convenances.",
        "Vous pensez avoir du panache. Vous avez eu de la chance. Nuance.",
      ],
    },

    // 3 — Étoile du cirque : et maintenant, le numéro de la ruine
    3: {
      launch: [
        "Mesdames, messieurs, sous le grand chapiteau : le pigeon volant !",
        "Roulement de tambour pour l'artiste qui va tout perdre : toi.",
        "Entre en piste, clown. Le public a payé pour te voir couler.",
        "Bienvenue au cirque. Ce soir, tu joues le rôle de la victime.",
        "Les projecteurs sur toi. Ils éclairent surtout tes poches vides.",
        "Prépare ton numéro. Spoiler : il finit dans le filet à jetons.",
        "T'as le trac ? Normal. Ton portefeuille aussi.",
        "Le funambule, c'est toi. La corde est déjà coupée.",
        "Applaudissez le futur ruiné qui entre en scène !",
        "Trois, deux, un… et c'est parti pour ta chute libre.",
      ],
      play: [
        "Tu jongles avec tes jetons ? Tu vas tous les faire tomber.",
        "Mise, l'artiste. Le public s'impatiente de te voir échouer.",
        "Ce numéro d'équilibre est pathétique. Tu vacilles déjà.",
        "T'as le nez rouge et la stratégie clownesque.",
        "Un tour de trapèze ? Tu vas rater la barre.",
        "Ce jeton s'envole vers le chapiteau. Il ne revient pas.",
        "Ton bluff a autant de finesse qu'un lancer de tarte.",
        "Le lion (moi) tourne autour de ta cage à billets.",
        "Décide, avant que le rideau te tombe dessus.",
        "Encore un pari acrobatique et bancal.",
        "Ta fortune fait le grand écart. Vers zéro.",
        "T'as les yeux d'un clown qui va pleurer sous le maquillage.",
        "Relance ou plie. Le cirque n'attend personne.",
        "Je fais disparaître ta mise dans le canon à confettis.",
        "Un artiste de ton niveau devrait au moins tomber avec panache.",
        "Doucement sur le fil, tu vas basculer dans la faillite.",
        "Encore une relance ratée. Le public rit, mais de toi.",
        "Le chapiteau va s'effondrer. Sur ta tirelire.",
        "T'as une paire ? Moi j'ai tout le cirque, les éléphants compris.",
        "Vas-y, mise gros. Fais un numéro spectaculaire avant de mourir sur scène.",
      ],
      lose: [
        "Et voilà le clou du spectacle : ta ruine, en direct !",
        "Applaudissez ! Le pigeon a tout perdu sous le chapiteau !",
        "Numéro terminé. Le filet a récupéré tes jetons. Pas toi.",
        "Tu t'es écrasé au sol. Le public adore, moi aussi.",
        "Rideau. Tes économies restent en coulisses. Avec moi.",
        "Le canon t'a tiré vers la sortie. Sans ton argent.",
        "Bravo, l'artiste : la chute la plus drôle de la saison.",
        "Je range tes rêves dans la malle aux accessoires.",
        "T'as la poisse d'un clown et la chance d'un lancer de couteaux raté.",
        "La ménagerie te raccompagne. Tes jetons rejoignent ma caisse.",
      ],
      win: [
        "Ohhh, le pigeon a réussi une pirouette. Un vrai miracle de piste.",
        "Profite des applaudissements. Le lion revient au prochain acte.",
        "Une victoire ? Le régisseur a dû se tromper de lumière.",
        "Salue le public. Rejoue avant qu'il quitte le chapiteau.",
        "Un coup d'éclat isolé. Ta carrière reste un fiasco.",
        "La chance t'a lancé une fleur. Elle lance des couteaux, d'habitude.",
        "Garde ton petit trophée. Je viens le confisquer à l'entracte.",
        "Beau numéro. Le prochain finit dans la fosse.",
        "Tu te crois tête d'affiche. T'es le numéro de warm-up.",
        "Un gain honnête sous le chapiteau. Ça brise l'ambiance.",
      ],
    },

    // 4 — Plage écarlate : va pleurer dans le sable
    4: {
      launch: [
        "Salut, beau bronzage. Ton compte, lui, va prendre froid.",
        "Pose ta serviette. Je vais t'essorer comme un maillot mouillé.",
        "Un mojito et une faillite, ça te dit ?",
        "T'as mis de l'huile ? Tu vas glisser direct dans le rouge.",
        "Bienvenue sur ma plage privée. Prix d'entrée : tout ton fric.",
        "La marée monte. Ton portefeuille, lui, va disparaître sous l'eau.",
        "Allonge-toi. Ça amortira l'annonce de ta ruine.",
        "Le sable est chaud, ton avenir financier est glacial.",
        "Un dernier plongeon avant la noyade ?",
        "Je te plume au soleil, tranquille, façon sieste.",
      ],
      play: [
        "Détends-toi, chéri. La ruine, c'est mieux les épaules relâchées.",
        "Mise. La vague suivante emporte tout de toute façon.",
        "T'as du sable dans le cerveau. C'est chronique ?",
        "Ta stratégie a la solidité d'un château de sable à marée haute.",
        "Le courant t'emmène vers le large. Vers moi, en fait.",
        "Ce jeton, la mer l'a déjà avalé.",
        "Tu bluffes en tongs. Ça manque de crédibilité.",
        "Un requin rôde autour de ton épargne. Devine qui.",
        "Décide, avant que le soleil te grille le peu de jugeote.",
        "Encore un pari mou comme une méduse échouée.",
        "Ta fortune fond plus vite qu'un esquimau en août.",
        "T'as les yeux plissés. De soleil ou de panique ?",
        "Relance ou plie. La plage ferme pas, mais ton compte si.",
        "J'enterre ta mise dans le sable. Tu la retrouveras jamais.",
        "Un vrai vacancier perdrait avec plus de sérénité.",
        "Doucement sur la planche, tu vas boire la tasse.",
        "Encore une relance qui sent la crème solaire périmée.",
        "La marée descend. Ton solde aussi. Coïncidence ? Non.",
        "T'as une paire ? Moi j'ai toute la baie.",
        "Vas-y, mise gros. Offre-toi un beau naufrage.",
      ],
      lose: [
        "Splash. Ton argent repose désormais avec les poissons.",
        "Marée basse totale sur ton compte. Rien. Nada. Le vide.",
        "T'as coulé en douceur. Le sourire aux lèvres, presque.",
        "Le sable a tout bu. Va pleurer dedans, ça se verra pas.",
        "Naufrage complet. Même les mouettes détournent le regard.",
        "Ton château de sable s'est effondré. Comme prévu par tout le monde.",
        "La vague a pris tes jetons et ta dignité. Elle est gourmande.",
        "T'es à sec, et j'ai même pas ouvert le parasol.",
        "Retour à la serviette, matelot. Fauché comme les blés secs.",
        "Fais une sieste. T'as bien mérité ta ruine, tu t'es donné du mal.",
      ],
      win: [
        "Tiens, une petite vaguelette de chance. Ça va vite refluer.",
        "T'as ramassé un coquillage. J'ai la plage, l'hôtel et le bar.",
        "Profite du soleil. L'orage débarque au prochain coup.",
        "Un gain ? La mer a dû confondre avec quelqu'un de doué.",
        "Rejoue vite, avant que la marée reprenne tout.",
        "Joli plongeon. Le suivant, c'est dans le bassin vide.",
        "Mets ça au frais dans la glacière. Je viens me servir.",
        "La chance t'a frôlé comme une méduse. Ça piquera ce soir.",
        "T'as gagné une bouée. Le bateau prend l'eau quand même.",
        "Tu crois surfer la vague. Tu vas te la prendre dans la face.",
      ],
    },
  },
};

if (typeof window !== 'undefined') window.CROUPIER_LINES = CROUPIER_LINES;
if (typeof module !== 'undefined' && module.exports) module.exports = { CROUPIER_LINES };
